### ISSUE TITLE
Explain swipe right/left & up/down [16-24h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/literacyapp-start-guide#3]
- [x] Create wireframe
- [x] Plan audio recordings
- [x] Plan animations

**Comment by gscdev** [comment]
@jogrimst I have created the wireframe for swipe 
[https://docs.google.com/presentation/d/1lq80HVL4FvyTpefKPrvCiPlnUkAH13KUeAtma5b3-u4/edit#slide=id.p](https://docs.google.com/presentation/d/1lq80HVL4FvyTpefKPrvCiPlnUkAH13KUeAtma5b3-u4/edit#slide=id.p)
