### ISSUE TITLE
Start application automatically after device reboot [1-2h]

### ISSUE THREAD

**Issue by gscdev** [literacyapp-org/literacyapp-start-guide#5]
Only during the first 7 days of usage (coordinate duration with LiteracyApp).

**Comment by jogrimst** [comment]
@gscdev @sladomic Eventually, we should probably integrate this app closer with the LiteracyApp. But for now, what about the following solution? Store the date of first startup in SharedPreferences. If the date of first startup is empty or no longer than 7 days ago, start application automatically after device reboot. Then we'll do the same for the LiteracyApp authentication (do not trigger after device reboot until more than 7 days have passed).
